version: '3.8'

services:
  database:
    container_name: database
    image: mongo:7.0.5
    restart: unless-stopped
    ports:
      -27018:27017
    volumes:
      - database:/data/tb
    networks:
     - network-despliegue

volumes:
  database:

networks:
  - network-despliegue